[TA-2421[KYC]: Handle not found
Peersyst/backend-shared-modules pull request #41
Opened 2024-03-22 16:50 UTC by obnol

# [TA-2421[KYC]: Handle not found

## Affected apps/packages

| Code | Package           |
| ---- | ----------------- |
| KYC  | packages/kyc          |

## Changes :hammer_and_wrench:

- Delete unnecessary ignores and returns in `kyc.controller`
- Add error handling in `kyc.service` + refactor repetitive calls

2024-03-22 17:26 UTC, AgustinMJ requested changes

2024-03-22 17:26 UTC, AgustinMJ commented on packages/kyc-module/src/kyc.service.ts
> +    private async getKycByUserId(userId: number): Promise<KycI> {
Aquests mètodes millor que estiguin a dalt de tot

2024-03-22 17:26 UTC, AgustinMJ commented on packages/kyc-module/src/kyc.controller.ts
> +        return this.kycService.getKyc(req.user.id);
Has provat que tiri bé l'error sense fer `reeturn await`? A vegades si no es fica el `await` en el `return` no es "handleja" perquè s'espera que el handlegi qui crida la funció, però en aquest cas no controlem qui la crida. Si ho has provat i va bé doncs genial ho podem deixar així doncs :)

2024-03-25 08:10 UTC, GuillemGarciaDev requested changes
Falta incrementar la version al package.json

2024-03-25 08:16 UTC, AgustinMJ approved these changes

2024-03-25 08:43 UTC, merged